# Site settings
email: electronicslab@icloud.com
baseurl: "http://marccobler.es"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Marc Cobler
description:
url: "http://marccobler.es"
twitter_username: kitusmark
default_img:

# Profile settings
name: Marc Cobler Cosmen
profile_img:
profile:
social:
  github: kitusmark

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
